### ISSUE TITLE
打开没反应

### ISSUE THREAD

**Issue by wkz2003** [Leon406/ToolsFx#1]
bin底下的两个都试过了，我下载的是withjre版本，系统是win10

**Comment by Leon406** [comment]
bat 启动脚本 拖到 cmd命令行 执行看下报错信息

**Comment by Leon406** [comment]
目前不支持 32位系统, 建议安装jdk,使用不带jre的版本

**Comment by Leon406** [comment]
已确认问题,请重新下载最新版本
