### ISSUE TITLE
窗口大小问题建议：保持上次窗口大小或者设置窗口大小！

### ISSUE THREAD

**Issue by TDM48325619** [Leon406/ToolsFx#136]
窗口置顶功能很好，由于笔记本屏幕较小，每次打开都要调节窗口大小才能多个窗口同步操作，如果再优化一下窗口指定大小或者保持上次窗口大小就更好了！

**Comment by Leon406** [comment]
https://github.com/Leon406/ToolsFx/wiki/FAQ
调整下缩放比例
