### ISSUE TITLE
能否增加各种校验和的计算功能

### ISSUE THREAD

**Issue by killeder** [Leon406/ToolsFx#139]
**ToolsFx版本及构建日期(如v1.15.1.beta2 2022-12-13):**

**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

**操作步骤(如运行ToolsFx.bat):**

**问题现象(如闪退):**

**报错信息(命令行运行ToolsFx.bat/ToolsFx):**

**Comment by Leon406** [comment]
目前只有CRC-32 CRC-64

https://github.com/Leon406/ToolsFx/blob/dev/app/src/test/kotlin/me/leon/hash/CrcTest.kt
是这种吗
