### ISSUE TITLE
无法设置中文语言

### ISSUE THREAD

**Issue by DeHby** [Leon406/ToolsFx#155]
**ToolsFx版本及构建日期(如v1.15.1.beta2 2022-12-13):**
release v1.16.0 

**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**
Windows 11 22H2

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**
openjdk version "1.8.0_362"

**操作步骤(如运行ToolsFx.bat):**
打开后

**问题现象(如闪退):**
系统语言为中文 软件界面却为英文
![image](https://github.com/Leon406/ToolsFx/assets/47233058/2fe3574b-1215-4b85-95e4-3e07be9adbea)

**报错信息(命令行运行ToolsFx.bat/ToolsFx):**
Active code page: 65001
Plugin Info:ApiPost v1.6.1 2022-12-25 Leon406
ApiPost
Plugin Info:Compression v1.2.0 2022-04-06 Leon406
Compression
Plugin Info:图片模块 v1.2.1 2022-12-29 Leon406
图片模块
Plugin Info:经纬度相关 v1.2.0 2022-04-06 Leon406
经纬度相关
loading SUCCEEDED
load http://www.hiencode.com/
undefined

**Comment by Leon406** [comment]
![image](https://github.com/Leon406/ToolsFx/assets/26186607/08888ebd-e5fb-45af-9db5-4f31ef325cfd)

**Comment by 21jfx552** [comment]
> ![image](https://github.com/Leon406/ToolsFx/assets/26186607/08888ebd-e5fb-45af-9db5-4f31ef325cfd)

又无法换成中文了。重启也没有效果。
