### ISSUE TITLE
RABBIT解密提示错误

### ISSUE THREAD

**Issue by luoam** [Leon406/ToolsFx#156]
Caused by: <eval>:115:16 Error: Malformed UTF-8 data

密文：U2FsdGVkX19QwGkcgD0fTjZxgijRzQOGbCWALh4sRDec2w6xsY/ux53Vuj/AMZBDJ87qyZL5kAf1fmAH4Oe13Iu435bfRBuZgHpnRjTBn5+xsDHONiR3t0+Oa8yG/tOKJMNUauedvMyN4v4QKiFunw==

key： ISCC

**Comment by Leon406** [comment]
https://www.sojson.com/encrypt_rabbit.html
请确认数据是否正常, 网页版也没有解密成功

**Comment by luoam** [comment]
> https://www.sojson.com/encrypt_rabbit.html 请确认数据是否正常, 网页版也没有解密成功

数据正确的，http://tools.jb51.net/password/aes_encode 可以解

**Comment by Leon406** [comment]
> > https://www.sojson.com/encrypt_rabbit.html 请确认数据是否正常, 网页版也没有解密成功
> 
> 数据正确的，http://tools.jb51.net/password/aes_encode 可以解



你说是rabbit,然后跟我说用aes解密

参考 https://github.com/Leon406/ToolsFx/wiki/PBE
