### ISSUE TITLE
mac 下双击没反应

### ISSUE THREAD

**Issue by zzqsmile** [Leon406/ToolsFx#162]
**ToolsFx版本及构建日期(如v1.15.1.beta2 2022-12-13):**

**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

**操作步骤(如运行ToolsFx.bat):**

**问题现象(如闪退):**

**报错信息(命令行运行ToolsFx.bat/ToolsFx):**

**Comment by zzqsmile** [comment]
mac下双击打不开

**Comment by Leon406** [comment]
请完整填写信息
