### ISSUE TITLE
大佬，怎么批量

### ISSUE THREAD

**Issue by xiaoxiaoliya** [Leon406/ToolsFx#20]
我想批量进行hex转base64,一行对应一个
但是事实并非如此，他们会成为一个整体转换了

**Comment by Leon406** [comment]
目前没有这个功能,等下个版本吧

**Comment by Leon406** [comment]
https://github.com/Leon406/ToolsFx/releases/tag/v1.10.1 prelease版本已发布,请自行替换相关jar包
