### ISSUE TITLE
进制转换问题

### ISSUE THREAD

**Issue by cubolia** [Leon406/ToolsFx#21]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**
Windows10 x64

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**
jdk 1.8

**操作步骤(如运行ToolsFx.bat):**

运行ToolsFx

**问题现象(如闪退):**

进制转换存在问题，如10进制转16进制，10进制转二进制等，大于10进制255的转换的数不对，是目前仅支持255以下的数吗？比如65535转换的二进制数就不对（编码IOS8859-1，其他编码格式也试过），FFFF转换出的数也是两个255，而不是65535

**报错信息:**

无

**Comment by Leon406** [comment]
转化前,会进行编码转换,这部分导致出现了问题,请用编解码模块的数据数据进行测试,简单转换 请用系统自带的进制转换

以下10进制可以正常转换
30446 21069 21482 33021 36825 26679
