### ISSUE TITLE
ApiPost返回的结果如何正确解析，字体太小如何更改

### ISSUE THREAD

**Issue by lsj8924** [Leon406/ToolsFx#23]
1.返回的结果同时包含unicode和字母，还有链接也多了\/这种转义字符。这种必须每次把Unicode手动复制过去再解析吗，可以自动解析吗？
  "response": {
    "id": 971507,
    "shop_id": "1jed4868g2039275b0",
    "chapter_id": 267465,
    "title": "\u7b2c\u4e00\u6a21\u5757 - \u7ecf\u6d4e\u5b66\u6838\u5fc3\u539f\u7406",
    "content": {
      "file_id": "5285890807763751977",
      "file_name": "\u6a21\u5757\u5b8c\u6574\u7248",
      "size": "282.68",
      "cover_url": "5285890807763751977",
      "patch": "https:\/\/duanshu-1253562005.image.myqcloud.com\/2020\/09\/18\/19\/1jed4868g2039275b0\/common\/content\/1600427476165_727846.png?imageMogr2\/auto-orient\/cut\/1912x1075x0x0",
      "is_first_frame": 0,
      "duration_seconds": 315,
      "video_patch": "https:\/\/vod.duanshu.com\/e4a62924vodtransgzp1253562005\/0e08201d5285890807763751977\/v.f230.m3u8?t=6200aa41&us=bqilkravwd&sign=1ae52af7247f4c3ca33e7bf7be574974",
   
}
2.如何自定义字体大小，字体确实有点小。
![image](https://user-images.githubusercontent.com/8875594/152668992-12dc038c-29b0-4d09-b377-d44b12ecfa75.png)

**Comment by Leon406** [comment]
字体的问题,是适配的的问题,暂时不会解决

https://github.com/Leon406/ToolsFx/releases/tag/v1.10.2 prelease版本已发布,请自行替换相关jar包
