### ISSUE TITLE
MAC计算时输入的消息只支持字符格式的吗？

### ISSUE THREAD

**Issue by songjinlian** [Leon406/ToolsFx#26]
MAC计算时输入的消息只支持字符格式的吗？是否考虑支持Hex格式的消息输入？

**Comment by Leon406** [comment]
https://leon.lanzoub.com/ibtSl01owrlg 可以先用开发版本,
下个正式版本和并入

**Comment by songjinlian** [comment]
> https://leon.lanzoub.com/ibtSl01owrlg 可以先用开发版本, 下个正式版本和并入

有发布的计划时间吗

**Comment by Leon406** [comment]
> 

暂无,先用开发版吧

**Comment by songjinlian** [comment]
> > 
> 
> 暂无,先用开发版吧

能指点一下开发版的具体使用方法吗？对于JAVA不熟悉

**Comment by Leon406** [comment]
> 

lib目录 删除 app-xxx.jar 文件,使用上面提供的文件

**Comment by songjinlian** [comment]
> > 
> 
> lib目录 删除 app-xxx.jar 文件,使用上面提供的文件

![图片](https://user-images.githubusercontent.com/101912268/159143276-b72aa051-306a-495d-94f0-8349ea192644.png)
测试了一下，输入还是按字符处理的

**Comment by songjinlian** [comment]
> 
可以了。编解码、哈希、签名与验签的输入还是字符格式的

**Comment by Leon406** [comment]
很多没用使用场景,就先不加了,如果有请先提供相关数据以供测试

有转码需求 可以通过 编码转换手动转换

**Comment by songjinlian** [comment]
> 很多没用使用场景,就先不加了,如果有请先提供相关数据以供测试
> 
> 有转码需求 可以通过 编码转换手动转换

哈希与MAC类似，很多场景输入的消息是hex格式的，转成字符会乱码。测试数据如下：
输入消息Hex格式
008031323334353637383132333435363738FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E9332C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0723d2b6753940cd6db1957551fcf1f940883d2ecc643c30128b17cbe226a3845dd8c60cd190afd32444579776cae34752f5d05488374ddfdb2f6a461a226b8b4
计算结果
SM3:
13784AB09BBBF2947D755D61C23D4C316C67B83BE4F8A4153C187C00335D4202

MD5:
5B3CCB40EF7654ABAD69C355E0ECD16E

SHA1:
D06C4838EA9DF8B18C31D8A2117F99663C8BE113

SHA256:
FB03A80D512CE70FD26B652FE759E699B04E44F638C7C8272A02A33BC2BCBA96

SHA384:
9A7872DE2848A2606108B30460221BC891D55261010DDA9C185A384AF7C6662388557618F936212A39102E29B1788868

SHA512:
9AA0569B00524BF7B07FA5A42BD94D58F16678419F12576916939F374909BD4ADA360AD412176363CAC33478EB8078EB6E7728086E740D56A91F518D9EA354C8

**Comment by Leon406** [comment]
> > 很多没用使用场景,就先不加了,如果有请先提供相关数据以供测试
> > 有转码需求 可以通过 编码转换手动转换
> 
> 哈希与MAC类似，很多场景输入的消息是hex格式的，转成字符会乱码。测试数据如下： 输入消息Hex格式 008031323334353637383132333435363738FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E9332C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0723d2b6753940cd6db1957551fcf1f940883d2ecc643c30128b17cbe226a3845dd8c60cd190afd32444579776cae34752f5d05488374ddfdb2f6a461a226b8b4 计算结果 SM3: 13784AB09BBBF2947D755D61C23D4C316C67B83BE4F8A4153C187C00335D4202
> 
> MD5: 5B3CCB40EF7654ABAD69C355E0ECD16E
> 
> SHA1: D06C4838EA9DF8B18C31D8A2117F99663C8BE113
> 
> SHA256: FB03A80D512CE70FD26B652FE759E699B04E44F638C7C8272A02A33BC2BCBA96
> 
> SHA384: 9A7872DE2848A2606108B30460221BC891D55261010DDA9C185A384AF7C6662388557618F936212A39102E29B1788868
> 
> SHA512: 9AA0569B00524BF7B07FA5A42BD94D58F16678419F12576916939F374909BD4ADA360AD412176363CAC33478EB8078EB6E7728086E740D56A91F518D9EA354C8

好的,收到需求,后续会加入

**Comment by songjinlian** [comment]
谢谢
