### ISSUE TITLE
签名验签的修订建议

### ISSUE THREAD

**Issue by songjinlian** [Leon406/ToolsFx#28]
密钥现在要求是PKCS格式的，对于采用数字证书验证的场景，从证书中提取时只有公钥，没有算法OID导致验证不通过。建议密钥增加Hex格式输入（如RSA算法，分别输入n，e值），原始内容增加Hex格式输入

**Comment by Leon406** [comment]
原始内容增加Hex格式输入  开发版本已经有了

其他的目前不考虑, 目前是支持文件拖入自动识别密钥后缀pem, cer , der,key,pk8

**Comment by songjinlian** [comment]
经测试，好用了。谢谢
