### ISSUE TITLE
建议编解码支持Hex输入

### ISSUE THREAD

**Issue by songjinlian** [Leon406/ToolsFx#29]
工具编码转换无法实现Hex转换为字符。无法计算Hex格式的Base64编码
如：
Hex格式：008031323334353637383132333435363738FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E9332C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0723d2b6753940cd6db1957551fcf1f940883d2ecc643c30128b17cbe226a3845dd8c60cd190afd32444579776cae34752f5d05488374ddfdb2f6a461a226b8b4
Base64编码：AIAxMjM0NTY3ODEyMzQ1Njc4/////v////////////////////8AAAAA//////////wo6fqenZ9eNE1ankvPZQmn85eJ9RWrj5LdvL1BTZQOkzLEriwfGYEZX5kERmo5yZSP4wu/8mYL4XFaRYkzTHTHvDc2ovT2d5xZvc7ja2khU9Cph3zGKkdAAt8y5SE58KByPStnU5QM1tsZV1Ufzx+UCIPS7MZDwwEosXy+Imo4Rd2MYM0ZCv0yREV5d2yuNHUvXQVIg3Td/bL2pGGiJri0
由于工具不支持Hex输入，无法计算

**Comment by Leon406** [comment]
没看懂, 是转的结果不对吗

**Comment by songjinlian** [comment]
> 没看懂, 是转的结果不对吗

【编解码】 输入不支持Hex格式，会导致非字符的Hex格式的输入无法正确计算。如要对如下Hex格式的进行Base64编码，则无法计算
008031323334353637383132333435363738FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E9332C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0723d2b6753940cd6db1957551fcf1f940883d2ecc643c30128b17cbe226a3845dd8c60cd190afd32444579776cae34752f5d05488374ddfdb2f6a461a226b8b4

**Comment by Leon406** [comment]
可以正常计算, 上面编码选择hex,下面选择base64

**Comment by Leon406** [comment]
![image](https://user-images.githubusercontent.com/26186607/161371398-afc8a418-fdf3-445d-9744-89ed775cd682.png)

**Comment by songjinlian** [comment]
谢谢
