### ISSUE TITLE
是否考虑增加大数计算功能？

### ISSUE THREAD

**Issue by songjinlian** [Leon406/ToolsFx#30]
是否考虑增加大数计算功能？

**Comment by Leon406** [comment]
需要哪些功能,有参考的软件吗
目前测试已实现RSA大数加解密

**Comment by songjinlian** [comment]
> 需要哪些功能,有参考的软件吗 目前测试已实现RSA大数加解密
Big Integer Calculator v1.13
[Uploading Big Integer Calculator v1.13.zip…]()

**Comment by Leon406** [comment]
> > 需要哪些功能,有参考的软件吗 目前测试已实现RSA大数加解密
> > Big Integer Calculator v1.13
> > Uploading Big Integer Calculator v1.13.zip…

文件上传失败了

**Comment by songjinlian** [comment]
> > > 需要哪些功能,有参考的软件吗 目前测试已实现RSA大数加解密
> > > Big Integer Calculator v1.13
> > > Uploading Big Integer Calculator v1.13.zip…
> 
> 文件上传失败了
[Big Integer Calculator v1.13.zip](https://github.com/Leon406/ToolsFx/files/8403653/Big.Integer.Calculator.v1.13.zip)

**Comment by Leon406** [comment]
测试版已经更新,从关于页面 网盘下载最新版本

**Comment by songjinlian** [comment]
> 测试版已经更新,从关于页面 网盘下载最新版本

![图片](https://user-images.githubusercontent.com/101912268/161656649-b62b8647-371c-4a42-b291-96d17bcc51e8.png)
1、16进制数的计算结果是10进制数，可否改为输出也是16进制数
2、是否可实现类似openss大数计算函数bn.h相应的功能，如计算(X-Y) mod Z

**Comment by Leon406** [comment]
第一点可以的
第二点的话,自带的不支持功能,需要额外实现,提供几组测试数据来调试

**Comment by Leon406** [comment]
最新修改的已经上传蓝奏,可以抢先下载试用,可能还存在问题

**Comment by songjinlian** [comment]
> 最新修改的已经上传蓝奏,可以抢先下载试用,可能还存在问题

![图片](https://user-images.githubusercontent.com/101912268/161681239-435b7bdf-72ac-45dd-a3eb-f7677b6d637c.png)
Y小于X时，计算出错

**Comment by songjinlian** [comment]
> 最新修改的已经上传蓝奏,可以抢先下载试用,可能还存在问题

测试了X-Y，（X/Y）mod Z，结果都正确
