### ISSUE TITLE
编解码无法判断二进制方式

### ISSUE THREAD

**Issue by GuoscWeb** [Leon406/ToolsFx#308]
**ToolsFx版本(ToolsFx-1.18.0-jdk8-withjre-windows-x86):**

**系统版本及位数(Window x64):**
**操作步骤(如运行ToolsFx.bat):**
将flag字符进行二进制转换、base58转换、base64转换（得到NW91QU5DanJBalRpWUhuRzdHdlVXQUNNVWpjM2FDNG9TMVJjNTVoaDhyaUpkSGdD）
再使用编解码，结果如下：所有To binary的都会判断为HexOctBin
1 base64-->2 base58(radix58)-->3 HexOctBin
0

**Comment by Leon406** [comment]
![image](https://github.com/user-attachments/assets/2d272c87-d0b6-4317-8ad7-96ba482a6eb4)
改下times, 设置下最小长度
