### ISSUE TITLE
带有中文的目录无法启动工具

### ISSUE THREAD

**Issue by nidemingzizj** [Leon406/ToolsFx#336]
**ToolsFx版本及构建日期(如v1.15.1.beta2 2022-12-13):**

**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

**操作步骤(如运行ToolsFx.bat):**

**问题现象(如闪退):**

**报错信息(命令行运行ToolsFx.bat/ToolsFx):**

**中文目录启动报错ctive code page: 65001:**

**Comment by Leon406** [comment]
改为英文目录吧

win 11 测试ToolsFx.bat/ToolsFx.exe都正常
![image](https://github.com/user-attachments/assets/0e8a10b8-bef0-4a0c-8a7c-da68bb40a045)

**Comment by nidemingzizj** [comment]
![image](https://github.com/user-attachments/assets/f42306ee-59bf-4d75-b0be-1b441daafde5)
我这边中文确实不行，不知道啥情况

**Comment by nidemingzizj** [comment]
![image](https://github.com/user-attachments/assets/cb5583b8-a5d6-485c-8d79-8e52e144fc1b)
我这边也是win11，问题不大感谢大佬

**Comment by Leon406** [comment]
> ![image](https://private-user-images.githubusercontent.com/30177896/383906657-f42306ee-59bf-4d75-b0be-1b441daafde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTA4ODUsIm5iZiI6MTczMDk5MDU4NSwicGF0aCI6Ii8zMDE3Nzg5Ni8zODM5MDY2NTctZjQyMzA2ZWUtNTliZi00ZDc1LWIwYmUtMWI0NDFkYWFmZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNDU5NDA4NzM2YTNjNzQyNjc0NDgwMzljZTAxYzE1MzFhZjBmOTZiYmQ5MTMyZTE1MGU2Mzk1MWY0MGU3YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bU4izGmAbdr5Pl1pDSQExPqxHESPeZ4sYk6IYJbJKw4) 我这边中文确实不行，不知道啥情况

应该是路径中 & 符号的问题，你可以把这个改掉在看看
