### ISSUE TITLE
mac下双击ToolsFx 直接以记事本打开，是怎么回事

### ISSUE THREAD

**Issue by douweigang** [Leon406/ToolsFx#42]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

**操作步骤(如运行ToolsFx.bat):**

**问题现象(如闪退):**

**报错信息:**

**Comment by douweigang** [comment]
错误: 找不到或无法加载主类 me.leon.MainKt
原因: java.lang.ClassNotFoundException: me.leon.MainKt
Saving session...completed.

**Comment by Leon406** [comment]
请补充前面的信息,便于分析问题

**Comment by douweigang** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Leon406** [comment]
终端执行以下命令看下
./ToolsFx

**Comment by douweigang** [comment]
已解决了，java版本不太对
大佬顺便弄个打包的mac版本呗

**Comment by Leon406** [comment]
没有mac电脑
