### ISSUE TITLE
GCM 和 CCM 算法的实现好像有问题。标准是四个参数。

### ISSUE THREAD

**Issue by xuyb6** [Leon406/ToolsFx#45]
在你的工具中GCM/CCM 加密模式中没有涉及 Associated Data ，这是不对的。
算法的最后还要生成一个Authentication Tag 认证标签。
可以参考RFC8998看看。

**Comment by Leon406** [comment]
https://en.wikipedia.org/wiki/Galois/Counter_Mode
The encrypted text then contains the IV, ciphertext, and authentication tag.

**Comment by Leon406** [comment]
如果有问题,请提供相关测试工具,及数据

**Comment by xuyb6** [comment]
请看参考RFC8998附录的测试数据 
![image](https://user-images.githubusercontent.com/104239985/164893645-5e710de2-2321-437e-ac1c-a8c17f605f06.png)

**Comment by Leon406** [comment]
目前默认 Associated Data为空,不支持添加,下个版本会加入AEAD mode, Associated Data输入

加密结果是含有Authentication Tag ,加密的长度,比明文多16字节,最后16个字节就是Authentication Tag

暂时可以先用这个工具
https://gchq.github.io/CyberChef/#recipe=AES_Encrypt(%7B'option':'UTF8','string':'1234567890123456'%7D,%7B'option':'UTF8','string':'1234567890123456'%7D,'GCM','Raw','Hex',%7B'option':'UTF8','string':'1234567812345678'%7D)&input=SGVsbG8xMjM0NTY3ODkwSGVsbG8xMjM0NTY3ODkw

**Comment by Leon406** [comment]
https://leon.lanzoub.com/b0d9av2kb 提取码：52pj 网盘已经上传 测试的jar包, AEAD  4个模式支持Associated Data输入

**Comment by xuyb6** [comment]
亲测，可用！ 非常棒！
