### ISSUE TITLE
将大数转换编码成二进制时报错

### ISSUE THREAD

**Issue by xuyb6** [Leon406/ToolsFx#48]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

windows10

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

jdk1.8

**操作步骤(如运行ToolsFx.bat):**
RSA2048经典大素数为：25195908475657893494027183240048398571429282126204032027777137836043662020707595556264018525880784406918290641249515082189298559149176184502808489120072844992687392807287776735971418347270261896375014971824691165077613379859095700097330459748808428401797429100642458691817195118746121515172654632282216869987549182422433637259085141865462043576798423387184774447920739934236584823824281198163815010674810451660377306056201619676256133844143603833904414952634432190114657544454178424020924616515723350778707749817125772467962926386356373289912154831438167899885040445364023527381951378636564391212010397122822120720357

**问题现象(如闪退):**

出错如下

**报错信息:**
<img width="957" alt="Snipaste_2022-05-06_14-45-16" src="https://user-images.githubusercontent.com/104239985/167082308-bdaf90b5-f5c9-4749-8ec5-a4b6d0c20fc3.png">

**Comment by xuyb6** [comment]
找了个工具可以完成转换这个事了。在求模数的时候，偶尔想了解下比特数。转换还是有必要的。用法是人定的，没有所谓的“乱用”之说。 密码不死板，本源多项式也可以有很多的选择呢。何况是编码问题。 
<img width="445" alt="Snipaste_2022-05-07_07-46-16" src="https://user-images.githubusercontent.com/104239985/167228526-4437182d-2757-46c6-b35e-d87daf9390f8.png">

**Comment by Leon406** [comment]
![image](https://user-images.githubusercontent.com/26186607/167231831-da07bd28-9fd1-40f0-b562-e8c39e9d325f.png)
demical 算法是这个,并没有问题,首先你得自己搞清楚

目前没有进制的功能, 后面会加相关进制相关算法支持

大部分个人在线的工具的正确性无法保证, 建议用CyberChef

https://gchq.github.io/CyberChef/#recipe=From_Base(10)To_Base(32)&input=MjUxOTU5MDg0NzU2NTc4OTM0OTQwMjcxODMyNDAwNDgzOTg1NzE0MjkyODIxMjYyMDQwMzIwMjc3NzcxMzc4MzYwNDM2NjIwMjA3MDc1OTU1NTYyNjQwMTg1MjU4ODA3ODQ0MDY5MTgyOTA2NDEyNDk1MTUwODIxODkyOTg1NTkxNDkxNzYxODQ1MDI4MDg0ODkxMjAwNzI4NDQ5OTI2ODczOTI4MDcyODc3NzY3MzU5NzE0MTgzNDcyNzAyNjE4OTYzNzUwMTQ5NzE4MjQ2OTExNjUwNzc2MTMzNzk4NTkwOTU3MDAwOTczMzA0NTk3NDg4MDg0Mjg0MDE3OTc0MjkxMDA2NDI0NTg2OTE4MTcxOTUxMTg3NDYxMjE1MTUxNzI2NTQ2MzIyODIyMTY4Njk5ODc1NDkxODI0MjI0MzM2MzcyNTkwODUxNDE4NjU0NjIwNDM1NzY3OTg0MjMzODcxODQ3NzQ0NDc5MjA3Mzk5MzQyMzY1ODQ4MjM4MjQyODExOTgxNjM4MTUwMTA2NzQ4MTA0NTE2NjAzNzczMDYwNTYyMDE2MTk2NzYyNTYxMzM4NDQxNDM2MDM4MzM5MDQ0MTQ5NTI2MzQ0MzIxOTAxMTQ2NTc1NDQ0NTQxNzg0MjQwMjA5MjQ2MTY1MTU3MjMzNTA3Nzg3MDc3NDk4MTcxMjU3NzI0Njc5NjI5MjYzODYzNTYzNzMyODk5MTIxNTQ4MzE0MzgxNjc4OTk4ODUwNDA0NDUzNjQwMjM1MjczODE5NTEzNzg2MzY1NjQzOTEyMTIwMTAzOTcxMjI4MjIxMjA3MjAzNTc

**Comment by Leon406** [comment]
目前的所有的算法,都没有加说明,不适合新手去使用

这也是我后面需要做的事情

**Comment by Leon406** [comment]
已新增radix10,radix8,raidx32
可以重新从网盘下载最新jar包
