### ISSUE TITLE
rot13解密之后的密文都是大写 无法再次加密回原来的密文

### ISSUE THREAD

**Issue by Laifang** [Leon406/ToolsFx#50]
如题 使用最新的版本 1.13.0

**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

**操作步骤(如运行ToolsFx.bat):**

**问题现象(如闪退):**

**报错信息:**

**Comment by Laifang** [comment]
[](http://img.lfs451.vip/pic/202205142045942.png)
[](http://img.lfs451.vip/pic/202205142045940.png)

**Comment by Leon406** [comment]
感谢反馈,下个版本优化

**Comment by Leon406** [comment]
pre-release版本已发布
删除 根目录下/lib/app-xxx.jar,再复制最新的app.jar即可体验
