### ISSUE TITLE
在win11 java16环境上 运行toolsfx，起不来 

### ISSUE THREAD

**Issue by DaoShiLingYuGeWu** [Leon406/ToolsFx#52]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**
Windows11x64 

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

java16

**操作步骤(如运行ToolsFx.bat):**
双击TOOLSFX.BAT或双击TOOLSFX.EXE，

**问题现象(如闪退):**
双击或以管理员权限运行TOOLSFX.BAT，CMD窗口一闪而过
双击或以管理员权限运行TOOLSFX.EXE，无任何反应

**报错信息:**
无

**补充信息:**
在win7，无java环境，双击TOOSFX.BAT或toolsfx.exe，均可以运行起来

**Comment by Leon406** [comment]
jdk 9+ 如果不用内嵌jre的,需要配置openjfx,以下是文件里有说明
[ToolsFx-1.13.0-jdk17-no-jfx-all-platform.zip](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-jdk17-no-jfx-all-platform.zip)

jdk8 使用以下即可,无需配置
[ToolsFx-1.13.0-jdk8-all-platform.zip](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-jdk8-all-platform.zip)

也可以使用带jre环境的
[ToolsFx-1.13.0-withjre-win-x64.7z](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-withjre-win-x64.7z)
[ToolsFx-1.13.0-jdk8-withjre-windows-x86.7z](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-jdk8-withjre-windows-x86.7z)

**Comment by DaoShiLingYuGeWu** [comment]
> jdk 9+ 如果不用内嵌jres的,需要配置openjfx,下面文件里有说明 [ToolsFx-1.13.0-jdk17-no-jfx-all-platform.zip](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-jdk17-no-jfx-all-platform.zip)
> 
> jdk8以下使用即可，独立配置 [ToolsFx-1.13.0-jdk8-all-platform.zip](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-jdk8-all-platform.zip)
> 
> 也可以使用带jre环境的 [ToolsFx-1.13.0-withjre-win-x64.7z ](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-withjre-win-x64.7z) [ToolsFx-1.13.0-jdk8-withjre-windows-x86.7z](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-jdk8-withjre-windows-x86.7z)

我下载和使用的是[ToolsFx-1.13.0-withjre-win-x64.7z](https://github.com/Leon406/ToolsFx/releases/download/v1.13.0/ToolsFx-1.13.0-withjre-win-x64.7z)，正常情况下，应该和操作系统环境无关，但win11上确实打不开，win7可以

**Comment by DaoShiLingYuGeWu** [comment]
![0PS_TG{@D%VLFO@EP)03_H1](https://user-images.githubusercontent.com/52524110/169032715-d646cf1c-dfdc-45dc-b2e3-4f8ee75eb8d8.png)提示这个，你分析下问题出哪了

**Comment by Leon406** [comment]
看起来像是 lib目录少了app jar，重新下载一个新的是否还有问题

**Comment by DaoShiLingYuGeWu** [comment]
有可能，我试试，虽然我个人认为问题大概率不是出在这里，毕竟这没法解释的通同样的文件，在win7环境下就可以运行的起来。

**Comment by DaoShiLingYuGeWu** [comment]
重新下了，在该win11环境确实没法用，原因未知

**Comment by DaoShiLingYuGeWu** [comment]
![image](https://user-images.githubusercontent.com/52524110/171072915-065bdb4b-5f8b-4e1c-967e-0f6a84b88883.png)
原因未知，现在在win11+java16的环境，可以使用，没对环境或toolfx有过任何改动，

**Comment by DaoShiLingYuGeWu** [comment]
补充一点，环境因素没变，但我将toolfx从桌面移到其他路径了，而且刚测了下，在桌面打开确实不行，但移至其他路径可以打开，怀疑是权限问题，具体原因或涉及的机制，还没搞懂。

**Comment by Leon406** [comment]
> 补充一点，环境因素没变，但我将toolfx从桌面移到其他路径了，而且刚测了下，在桌面打开确实不行，但移至其他路径可以打开，怀疑是权限问题，具体原因或涉及的机制，还没搞懂。

杀毒软件关了看看

**Comment by DaoShiLingYuGeWu** [comment]
> > 补充一点，环境因素没有改变，我将toolfx从桌面打开到其他路径了，而且刚测了下，在桌面打开确实不行，但至其他路径可以，怀疑是权限问题，具体但原因或涉及的机械，搞懂。
> 
> 杀毒软件关了看看

因为在搞渗透，运行成功和运行不成功时都没开杀毒软件，唯一的区别是把toolfx移动到其他路径下了，后面我还专门把toofx移回到桌面试过，确实在桌面上运行是无法成功的。可移到其他路径下就又可以运行成功了。

**Comment by songjinlian** [comment]
> 

路径包含中文了？

**Comment by DaoShiLingYuGeWu** [comment]
> > 
> 
> 路径包含中文了？

不是，放置在桌面时路径不包含中文，移动后的文件所在路径才存在中文，有中文不影响启动。
