### ISSUE TITLE
建议对称加密优化

### ISSUE THREAD

**Issue by chinapee** [Leon406/ToolsFx#53]
Windows11
对称加密中以文件模式进行解密后，选择输出内容raw、base64、hex 选择任一项输出内容都是一样的，我想要的是16进制编码，结果输出文件打开是乱码，必须用其它编辑器在二进制下才能看到数据，无法直接获得数据。

**Comment by Leon406** [comment]
文件模式不支持输出编码, 加密的都是二进制,文件也是二进制
这个不会修改,如有需求请使用文本加密
