### ISSUE TITLE
命令行解密，怎么运行？

### ISSUE THREAD

**Issue by nissansz** [Leon406/ToolsFx#54]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**
1.8

**操作步骤(如运行ToolsFx.bat):**
命令行解密，怎么运行？

**问题现象(如闪退):**
命令行解密，怎么运行？

**报错信息:**
命令行解密，怎么运行？

**Comment by Leon406** [comment]
目前不支持

**Comment by nissansz** [comment]
想问下，python或java怎么将html文件读取成raw格式？

**Comment by Leon406** [comment]
> 想问下，python或java怎么将html文件读取成raw格式？

是压缩过的吗?

**Comment by nissansz** [comment]
[chap4.zip](https://github.com/Leon406/ToolsFx/files/8740416/chap4.zip)
Check this.

**Comment by Leon406** [comment]
在线的链接发下,如果在线的无法正常显示就是加密过的

**Comment by nissansz** [comment]
是的，但是我只需要讀取成raw格式，把他讀取出來，類似下面這種效果。

e = "eaCq6m4+514bwRyRAyWJe7a0JFg+ZKz4zlNBG8BajhX0+zkXCFC+5oy2q5MElAJXlI52d9dMoN6JOASn3MEBpKaYm/iVG7cTr3GPD2SctKP3ySY9Rt38N+eztzEdZTYMywAXEsmkbcUIWrE/bHfnaPepckF9WFssFqMseh0q03PQxzIBPRkxnpKMXUhMyyPXepBuOZjOoJr。。。。。。。。。。。。。

**Comment by Leon406** [comment]
加密的,请自己寻找解密算法和密钥

**Comment by nissansz** [comment]
用你的软件可以解密。但是我想要读取出raw的代码，简化操作

**Comment by Leon406** [comment]
知道加密算法,就自己解密,一般来说命令行,openssl都可以解密

**Comment by nissansz** [comment]
openssl是什么？怎么写个Java代码？

**Comment by Leon406** [comment]
自己搜索引擎

**Comment by nissansz** [comment]
发现是读成 base64就可以了
