### ISSUE TITLE
软件界面多处使用图标，尤其是字符处理界面，但无提示文字，新手不友好，建议添加鼠标悬停提示

### ISSUE THREAD

**Issue by wolfyu1991** [Leon406/ToolsFx#55]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**
Windows 10

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**
ToolsFx-1.13.0-withjre-win-x64

**操作步骤(如运行ToolsFx.bat):**

**问题现象(如闪退):**
软件界面多处使用图标，尤其是字符处理界面，但无提示文字，新手不友好，建议添加鼠标悬停提示

**报错信息:**

**Comment by Leon406** [comment]
感谢反馈
