### ISSUE TITLE
Mac OSX启动闪退

### ISSUE THREAD

**Issue by BlazeLuLu** [Leon406/ToolsFx#57]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**
Mac OSX Monterey 12.4

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

**操作步骤(如运行ToolsFx.bat):**
chmod +x ./ToolsFx
双击根目录下ToolsFx后闪退

**问题现象(如闪退):**
闪退

**报错信息:**
错误: 找不到或无法加载主类 me.leon.MainKt

不知道是哪步操作的不对还是java环境有问题

**Comment by Leon406** [comment]
文档已经明确说明 jdk8用oracle官方的的jdk了
AdoptOpenJDK删除了javafx, 所以闪退
