### ISSUE TITLE
CTF中RSA质因数分解报错

### ISSUE THREAD

**Issue by songjinlian** [Leon406/ToolsFx#58]
采用/testdata/ctf/rsa/n2.txt测试数据报错如下，是使用方法不对吗？
![图片](https://user-images.githubusercontent.com/101912268/179132733-1aa1d0ee-4f69-44ae-9d4e-b6743e99fe05.png)

**Comment by Leon406** [comment]
这个不是这么用的, 这是测试用例里分解的数据
s
请用rsa开头文件测试

**Comment by songjinlian** [comment]
> 这个不是这么用的, 这是测试用例里分解的数据,目前没有单独使用地方 https://github.com/Leon406/ToolsFx/blob/2a2dec9de4ccedd27135d4ae3a8f4fc27151c245/app/src/test/kotlin/me/leon/math/factor/FactorTest.kt
> 
> 请用rsa开头文件进行功能测试

是否考虑增加通过p、q、e求解d值计算？

**Comment by Leon406** [comment]
不会,简单的用大数模块 算

**Comment by Leon406** [comment]
网盘已更新 大数模块

e^-1 % (P-1)(Q-1)   求d
C^d mod N    RSA 解密
