### ISSUE TITLE
运行bat 报错 v1.14

### ISSUE THREAD

**Issue by lcy1225** [Leon406/ToolsFx#64]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**
Windows

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**
jdk 1.8.0

**操作步骤(如运行ToolsFx.bat):**
运行ToolsFx.bat

**问题现象(如闪退):**
闪退

**报错信息:**

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by Leon406** [comment]
更换成oracle官方 jdk
或者使用带jre环境的包
