### ISSUE TITLE
unicode编码

### ISSUE THREAD

**Issue by seeblog** [Leon406/ToolsFx#65]
关于unicode编解码结果有个疑问  

使用其他编码工具unicode 123456 > \u0031\u0032\u0033\u0034\u0035\u0036       
//自身工具可解码 123456 √    网页unicode编码选项可解码为123456 √  ToolsFx可以解码为123456 √

ToolsFx   unicode                123456 > \u31\u32\u33\u34\u35\u36
//自身工具可解码 123456 √   网页unicode编码选项无法解码 x                其他编码工具unicode无法解码 x     提示十六进制位数不足

使用hiencode.com - ASCII编码转换 123456 UTF-16 > \u0031\u0032\u0033\u0034\u0035\u0036(ToolsFx没有这个选项) 
Unicode也不相同

**Comment by Leon406** [comment]
感谢反馈， 编码的确有点问题，下个版本不足四位进行补零操作

**Comment by Leon406** [comment]
网盘jar包已更新
