### ISSUE TITLE
1.14.4bete版本特别模糊

### ISSUE THREAD

**Issue by Tukali** [Leon406/ToolsFx#68]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

macos  m1   13版本

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

jdk1.8/openjdk

**操作步骤(如运行ToolsFx.bat):**

正常运行

**问题现象(如闪退):**

和1.14.3相比，极为模糊，切换回1.14.3就没问题了,对比如下
<img width="984" alt="CleanShot 2022-10-10 at 17 10 16@2x" src="https://user-images.githubusercontent.com/45891208/194833015-65297395-81f1-4ecf-9935-8a7e633e35db.png">

<img width="973" alt="CleanShot 2022-10-10 at 17 11 07@2x" src="https://user-images.githubusercontent.com/45891208/194833132-296dcd09-ba9a-4d06-9d42-d22e55f57001.png">

**报错信息:**

**Comment by Leon406** [comment]
![image](https://user-images.githubusercontent.com/26186607/194972628-7989fb88-61cf-4e48-9bb1-5a2a6d2fa089.png)

开启Hidpi重启看看

**Comment by Tukali** [comment]
> ![image](https://user-images.githubusercontent.com/26186607/194972628-7989fb88-61cf-4e48-9bb1-5a2a6d2fa089.png)
> 
> 开启Hidpi重启看看

可以了，开启之后就正常了
