### ISSUE TITLE
ToolFx v1.14.5 beta版本字体过小

### ISSUE THREAD

**Issue by jeffhardy0901** [Leon406/ToolsFx#69]
**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

windows 10 x64

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**
jdk 1.8.0 x86

**操作步骤(如运行ToolsFx.bat):**
ToolsFx.exe

**问题现象(如闪退):**
ToolFx v1.14.5 beta版本字体过小（v1.14.0无此问题）

**报错信息:**
无

**Comment by Leon406** [comment]
see https://github.com/Leon406/ToolsFx/issues/68
