### ISSUE TITLE
base64编码不支持视频文件吗

### ISSUE THREAD

**Issue by lsj8924** [Leon406/ToolsFx#70]
mp4格式的视频，直接拖进去说文件格式不支持，要不就是大于128KB不支持。

**Comment by Leon406** [comment]
不建议编码 非文本内容, 文件渲染会出现未响应的情况

**Comment by lsj8924** [comment]
找到方法了，问题可以关闭。把MP4放到16进制编辑器，复制16进制文本，然后在转换。如图：
![image](https://user-images.githubusercontent.com/8875594/200280202-d5d92ccf-ca7c-469d-a048-78515152e679.png)
