### ISSUE TITLE
aaencode失败

### ISSUE THREAD

**Issue by huanzhiyi** [Leon406/ToolsFx#77]
https://www.jsjiami.com/aaencode.html
这站加密了一段代码
但测试后发现提示Error: Given code is not encoded as aaencode. 

请问这种类型有办法解吗？

**Comment by Leon406** [comment]
如果其他在线的解不了,我这用不了,用的是同一个js,这个是应该是修改过的

**Comment by huanzhiyi** [comment]
感谢您的来信！

**Comment by huanzhiyi** [comment]
> 如果其他在线的解不了,ToolsFx也解不了,用的是同一个js,这个是应该是修改过的

嗯，应该是修改过的 那估计也解不了  感谢解答
