### ISSUE TITLE
文件逐行解密报错

### ISSUE THREAD

**Issue by lsj8924** [Leon406/ToolsFx#78]
解码错误: java.lang.NumberFormatException: For input string: "00-10000" under radix 2
![20230119222851](https://user-images.githubusercontent.com/8875594/213468717-68cb8d7f-c962-4461-ab8d-c84894406648.png)

**Comment by Leon406** [comment]
取消勾选文件模式或者逐行， 文件模式+逐行后面加的，功能还不完善

**Comment by Leon406** [comment]
nightly版本已更新, 限制只能选一个了

**Comment by lsj8924** [comment]
> nightly版本已更新, 限制只能选一个了

哪怕就是单行解密，只勾选文件模式，解密出来的文件是空的。

**Comment by Leon406** [comment]
文件上传下

**Comment by lsj8924** [comment]
[txtxtx.txt](https://github.com/Leon406/ToolsFx/files/10463880/txtxtx.txt)


![Ref](https://user-images.githubusercontent.com/8875594/213635357-425f7db4-62cd-458b-bbf6-9cd1f6a30fb3.gif)

**Comment by Leon406** [comment]
你文件上传就是空白的

**Comment by Leon406** [comment]
找到原因了,文件覆盖了,nightly更新了

**Comment by lsj8924** [comment]
非常感谢，测试单行已经成功。希望以后可以文件逐行解密。
![image](https://user-images.githubusercontent.com/8875594/213655617-bbdaf17b-1e49-412b-8465-ba19a46eb034.png)
