### ISSUE TITLE
plugin-image插件升级1.3.0后无法运行程序

### ISSUE THREAD

**Issue by Flamiec** [Leon406/ToolsFx#80]
**ToolsFx版本及构建日期(如v1.15.1.beta2 2022-12-13):**

ToolsFx v1.15.3.beta build 2023-02-01

**系统版本及位数(Windows/OSX/ Linux /x86/x64/ arm):**

Windows11

**Java版本(jdk 1.8.0 x86 oracle/openjdk):**

jdk 11 x64 openjdk

**操作步骤(如运行ToolsFx.bat):**

运行ToolsFx.exe\ToolsFx.bat都不行

**问题现象(如闪退):**

不知道为啥plugin-image插件替换为1.3.0的后，然后程序就打不开了，反复试验确定是插件的问题。

**报错信息:**

无显示报错信息

**Comment by Leon406** [comment]
命令行运行  ToolsFx.bat 发下报错信息

**Comment by Leon406** [comment]
插件是从网盘下载的,还是从github action下载
如果是github action下载, 请先从网盘下载插件后,再从github action下载

**Comment by Leon406** [comment]
从github action下载最新的app.jar覆盖, 应该先复制 v1.15.3.beta zip文件,再复制插件里文件
